/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAuthenticatedRouteImport } from './routes/_authenticated/authenticated'
import { Route as ProjectProjectIdPublicRouteImport } from './routes/project.$projectId.public'
import { Route as AuthenticatedProjectProjectIdRouteImport } from './routes/_authenticated/project.$projectId'
import { Route as AuthenticatedProjectProjectIdIndexRouteImport } from './routes/_authenticated/project.$projectId.index'
import { Route as AuthenticatedProjectProjectIdSettingsRouteImport } from './routes/_authenticated/project.$projectId.settings'

const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuthenticatedRoute =
  AuthenticatedAuthenticatedRouteImport.update({
    id: '/authenticated',
    path: '/authenticated',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ProjectProjectIdPublicRoute = ProjectProjectIdPublicRouteImport.update({
  id: '/project/$projectId/public',
  path: '/project/$projectId/public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectProjectIdRoute =
  AuthenticatedProjectProjectIdRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectProjectIdIndexRoute =
  AuthenticatedProjectProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectProjectIdRoute,
  } as any)
const AuthenticatedProjectProjectIdSettingsRoute =
  AuthenticatedProjectProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedProjectProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/project/$projectId': typeof AuthenticatedProjectProjectIdRouteWithChildren
  '/project/$projectId/public': typeof ProjectProjectIdPublicRoute
  '/project/$projectId/settings': typeof AuthenticatedProjectProjectIdSettingsRoute
  '/project/$projectId/': typeof AuthenticatedProjectProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/project/$projectId/public': typeof ProjectProjectIdPublicRoute
  '/project/$projectId/settings': typeof AuthenticatedProjectProjectIdSettingsRoute
  '/project/$projectId': typeof AuthenticatedProjectProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/_authenticated/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/_authenticated/project/$projectId': typeof AuthenticatedProjectProjectIdRouteWithChildren
  '/project/$projectId/public': typeof ProjectProjectIdPublicRoute
  '/_authenticated/project/$projectId/settings': typeof AuthenticatedProjectProjectIdSettingsRoute
  '/_authenticated/project/$projectId/': typeof AuthenticatedProjectProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/authenticated'
    | '/project/$projectId'
    | '/project/$projectId/public'
    | '/project/$projectId/settings'
    | '/project/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/authenticated'
    | '/project/$projectId/public'
    | '/project/$projectId/settings'
    | '/project/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/callback'
    | '/_authenticated/authenticated'
    | '/_authenticated/project/$projectId'
    | '/project/$projectId/public'
    | '/_authenticated/project/$projectId/settings'
    | '/_authenticated/project/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  ProjectProjectIdPublicRoute: typeof ProjectProjectIdPublicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/authenticated': {
      id: '/_authenticated/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedAuthenticatedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/project/$projectId/public': {
      id: '/project/$projectId/public'
      path: '/project/$projectId/public'
      fullPath: '/project/$projectId/public'
      preLoaderRoute: typeof ProjectProjectIdPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/project/$projectId': {
      id: '/_authenticated/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/$projectId/': {
      id: '/_authenticated/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectProjectIdRoute
    }
    '/_authenticated/project/$projectId/settings': {
      id: '/_authenticated/project/$projectId/settings'
      path: '/settings'
      fullPath: '/project/$projectId/settings'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdSettingsRouteImport
      parentRoute: typeof AuthenticatedProjectProjectIdRoute
    }
  }
}

interface AuthenticatedProjectProjectIdRouteChildren {
  AuthenticatedProjectProjectIdSettingsRoute: typeof AuthenticatedProjectProjectIdSettingsRoute
  AuthenticatedProjectProjectIdIndexRoute: typeof AuthenticatedProjectProjectIdIndexRoute
}

const AuthenticatedProjectProjectIdRouteChildren: AuthenticatedProjectProjectIdRouteChildren =
  {
    AuthenticatedProjectProjectIdSettingsRoute:
      AuthenticatedProjectProjectIdSettingsRoute,
    AuthenticatedProjectProjectIdIndexRoute:
      AuthenticatedProjectProjectIdIndexRoute,
  }

const AuthenticatedProjectProjectIdRouteWithChildren =
  AuthenticatedProjectProjectIdRoute._addFileChildren(
    AuthenticatedProjectProjectIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAuthenticatedRoute: typeof AuthenticatedAuthenticatedRoute
  AuthenticatedProjectProjectIdRoute: typeof AuthenticatedProjectProjectIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuthenticatedRoute: AuthenticatedAuthenticatedRoute,
  AuthenticatedProjectProjectIdRoute:
    AuthenticatedProjectProjectIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  ProjectProjectIdPublicRoute: ProjectProjectIdPublicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
