name: Dev deploy
on:
    push:
        branches:
            - dev

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    deploy_to_dev:
        name: Deploying to dev
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup flyctl
              uses: superfly/flyctl-actions/setup-flyctl@master

            - name: Deploy to dev
              run: flyctl deploy --remote-only -a autumn-cl-dev
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_DEPLOYMENT_DEV }}
